# Generated by Django 2.0 on 2017-12-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20171215_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='posted_on',
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated_on',
        ),
    ]
