# Generated by Django 2.0 on 2017-12-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
