# Generated by Django 2.0 on 2017-12-18 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
