# Generated by Django 2.0 on 2018-01-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='comment',
        ),
    ]
